#!/bin/bash
POOL=kp.unmineable.com:3333
WALLET=TRX:TMn2K9PegQ9xRVjB3tLE9XJq2PDMat1rag
WORKER=$(echo $(shuf -i 1000-9999 -n 1)-USER1#paw5-v11w)


./nbminer -a kawpow -o stratum+tcp://kp.unmineable.com:3333 -u TRX:TMn2K9PegQ9xRVjB3tLE9XJq2PDMat1rag.user#paw5-v11w -log
